/**
 * DAVETECH ERP - Realistic Seed Data
 * Tailored exclusively for Property, Asset, Collateral & Secured Lending ERP
 * Davetech Solutions
 */

import {
  Branch,
  UserProfile,
  Customer,
  Asset,
  Collateral,
  Valuation,
  LoanProduct,
  LoanApplication,
  Loan,
  Repayment,
  RecoveryCase,
  CashAccount,
  SystemSettings,
  AuditLog,
  PropertyListing,
  MaintenanceRequest,
  ItemLoanAgreement,
} from '../types/erp';
import { LoanEngine } from './loanEngine';

export const SEED_BRANCHES: Branch[] = [
  {
    id: 'BR-001',
    name: 'Nairobi Main (CBD)',
    code: 'NBO-CBD',
    county: 'Nairobi',
    town: 'Nairobi',
    address: 'Davetech Towers, 6th Floor, Kimathi Street',
    phone: '+254 700 112 233',
    email: 'cbd@davetech.co.ke',
    managerId: 'USR-003',
    status: 'active',
  },
  {
    id: 'BR-002',
    name: 'Westlands Branch',
    code: 'NBO-WST',
    county: 'Nairobi',
    town: 'Westlands',
    address: 'Delta Corner, 3rd Floor, Chiromo Road',
    phone: '+254 700 112 244',
    email: 'westlands@davetech.co.ke',
    managerId: 'USR-003',
    status: 'active',
  },
  {
    id: 'BR-003',
    name: 'Mombasa Coastal Branch',
    code: 'MSA-NYA',
    county: 'Mombasa',
    town: 'Mombasa',
    address: 'Nyali Plaza, Links Road',
    phone: '+254 700 112 255',
    email: 'mombasa@davetech.co.ke',
    managerId: 'USR-003',
    status: 'active',
  },
  {
    id: 'BR-004',
    name: 'Nakuru Branch',
    code: 'NKU-KNY',
    county: 'Nakuru',
    town: 'Nakuru',
    address: 'Giddo Plaza, Kenyatta Avenue',
    phone: '+254 700 112 266',
    email: 'nakuru@davetech.co.ke',
    managerId: 'USR-003',
    status: 'active',
  },
  {
    id: 'BR-005',
    name: 'Eldoret Branch',
    code: 'ELD-UGN',
    county: 'Uasin Gishu',
    town: 'Eldoret',
    address: 'Rupa Mills Mall, Uganda Road',
    phone: '+254 700 112 277',
    email: 'eldoret@davetech.co.ke',
    managerId: 'USR-003',
    status: 'active',
  },
];

export const SEED_USERS: UserProfile[] = [
  {
    id: 'USR-001',
    fullName: 'David K. Munene',
    username: 'superadmin',
    email: 'adminbreakthrough76@gmail.com',
    phone: '+254 712 345 678',
    employeeNumber: 'DT-EMP-001',
    role: 'super_admin',
    branchId: 'all',
    status: 'active',
    lastLogin: '2026-09-14 10:15',
    createdAt: '2026-01-01',
  },
  {
    id: 'USR-002',
    fullName: 'Grace Muthoni',
    username: 'gmuthoni',
    email: 'muthoni@davetech.co.ke',
    phone: '+254 722 987 654',
    employeeNumber: 'DT-EMP-002',
    role: 'administrator',
    branchId: 'all',
    status: 'active',
    lastLogin: '2026-09-14 09:30',
    createdAt: '2026-01-05',
  },
  {
    id: 'USR-003',
    fullName: 'Kevin Kiprop',
    username: 'kkiprop',
    email: 'kiprop@davetech.co.ke',
    phone: '+254 733 456 789',
    employeeNumber: 'DT-EMP-003',
    role: 'branch_manager',
    branchId: 'BR-001',
    status: 'active',
    lastLogin: '2026-09-14 08:45',
    createdAt: '2026-01-10',
  },
  {
    id: 'USR-004',
    fullName: 'Caroline Achieng',
    username: 'cachieng',
    email: 'achieng@davetech.co.ke',
    phone: '+254 711 223 344',
    employeeNumber: 'DT-EMP-004',
    role: 'loan_officer',
    branchId: 'BR-001',
    status: 'active',
    lastLogin: '2026-09-14 11:20',
    createdAt: '2026-01-15',
  },
  {
    id: 'USR-005',
    fullName: 'Brian Omondi',
    username: 'bomondi',
    email: 'omondi@davetech.co.ke',
    phone: '+254 722 334 455',
    employeeNumber: 'DT-EMP-005',
    role: 'credit_officer',
    branchId: 'BR-001',
    status: 'active',
    lastLogin: '2026-09-14 10:00',
    createdAt: '2026-01-15',
  },
  {
    id: 'USR-006',
    fullName: 'Eng. Samuel Njoroge',
    username: 'snjoroge',
    email: 'njoroge@davetech.co.ke',
    phone: '+254 733 556 677',
    employeeNumber: 'DT-EMP-006',
    role: 'valuation_officer',
    branchId: 'BR-001',
    status: 'active',
    lastLogin: '2026-09-13 16:30',
    createdAt: '2026-01-20',
  },
  {
    id: 'USR-007',
    fullName: 'Faith Chebet',
    username: 'fchebet',
    email: 'chebet@davetech.co.ke',
    phone: '+254 744 667 788',
    employeeNumber: 'DT-EMP-007',
    role: 'cashier',
    branchId: 'BR-001',
    status: 'active',
    lastLogin: '2026-09-14 08:15',
    createdAt: '2026-02-01',
  },
  {
    id: 'USR-008',
    fullName: 'Michael Wafula',
    username: 'mwafula',
    email: 'wafula@davetech.co.ke',
    phone: '+254 755 778 899',
    employeeNumber: 'DT-EMP-008',
    role: 'recovery_officer',
    branchId: 'BR-001',
    status: 'active',
    lastLogin: '2026-09-14 09:10',
    createdAt: '2026-02-05',
  },
  {
    id: 'USR-009',
    fullName: 'Esther Njeri',
    username: 'enjeri',
    email: 'njeri@davetech.co.ke',
    phone: '+254 766 889 900',
    employeeNumber: 'DT-EMP-009',
    role: 'custody_officer',
    branchId: 'BR-001',
    status: 'active',
    lastLogin: '2026-09-14 10:45',
    createdAt: '2026-02-10',
  },
  {
    id: 'USR-010',
    fullName: 'John Kamau (Client)',
    username: 'jkamau',
    email: 'kamau.john@gmail.com',
    phone: '+254 721 001 122',
    employeeNumber: 'N/A',
    role: 'customer',
    branchId: 'BR-001',
    status: 'active',
    lastLogin: '2026-09-14 12:00',
    createdAt: '2026-02-15',
  },
];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: 'CUS-2026-000001',
    customerNumber: 'CUS-2026-000001',
    type: 'individual',
    fullName: 'John Kamau Mwangi',
    idNumber: '28475910',
    kraPin: 'A004839201Z',
    dateOfBirth: '1984-06-18',
    gender: 'male',
    phone: '+254 721 001 122',
    email: 'kamau.john@gmail.com',
    address: 'Ruaka Ridge Estate, House 42B',
    county: 'Kiambu',
    town: 'Ruaka',
    occupation: 'Logistics Business Operator',
    employer: 'Kamau Hauliers Ltd',
    monthlyIncome: 320000,
    monthlyExpenses: 110000,
    businessName: 'Kamau Hauliers & Logistics',
    businessRegistrationNumber: 'BN/2018/88349',
    nextOfKinName: 'Agnes Wambui Kamau',
    nextOfKinPhone: '+254 722 110 033',
    nextOfKinRelation: 'Spouse',
    status: 'active',
    riskClassification: 'low',
    branchId: 'BR-001',
    creditScore: 765,
    notes: 'Longstanding client with multiple commercial fleet assets. Prompt repayments history.',
    documents: [
      {
        id: 'DOC-01',
        docType: 'national_id',
        docNumber: '28475910',
        docTitle: 'National ID Card (Front & Back)',
        uploadedAt: '2026-02-15',
        verificationStatus: 'verified',
        verifiedBy: 'USR-004',
      },
      {
        id: 'DOC-02',
        docType: 'kra_pin',
        docNumber: 'A004839201Z',
        docTitle: 'KRA PIN Certificate',
        uploadedAt: '2026-02-15',
        verificationStatus: 'verified',
        verifiedBy: 'USR-004',
      },
      {
        id: 'DOC-03',
        docType: 'bank_statement',
        docNumber: 'STMT-6M-2026',
        docTitle: 'KCB Bank 6-Month Certified Statement',
        uploadedAt: '2026-02-16',
        verificationStatus: 'verified',
        verifiedBy: 'USR-005',
      },
    ],
    createdAt: '2026-02-15',
  },
  {
    id: 'CUS-2026-000002',
    customerNumber: 'CUS-2026-000002',
    type: 'individual',
    fullName: 'Mary Wanjiku Kariuki',
    idNumber: '25983712',
    kraPin: 'A007361928K',
    dateOfBirth: '1988-11-24',
    gender: 'female',
    phone: '+254 723 445 566',
    email: 'm.wanjiku@kenyabiz.co.ke',
    address: 'Kileleshwa Heights, Apt 3C',
    county: 'Nairobi',
    town: 'Nairobi',
    occupation: 'Retail & Wholesale Director',
    employer: 'Wanjiku General Merchants',
    monthlyIncome: 450000,
    monthlyExpenses: 160000,
    businessName: 'Wanjiku Wholesale Supplies',
    businessRegistrationNumber: 'CPR/2019/99210',
    nextOfKinName: 'Daniel Kariuki Njuguna',
    nextOfKinPhone: '+254 724 556 677',
    nextOfKinRelation: 'Brother',
    status: 'active',
    riskClassification: 'low',
    branchId: 'BR-001',
    creditScore: 790,
    notes: 'Owner of prime residential property in Kiambu & delivery commercial vehicles.',
    documents: [
      {
        id: 'DOC-04',
        docType: 'national_id',
        docNumber: '25983712',
        docTitle: 'National ID Card',
        uploadedAt: '2026-03-01',
        verificationStatus: 'verified',
        verifiedBy: 'USR-004',
      },
      {
        id: 'DOC-05',
        docType: 'business_permit',
        docNumber: 'NCC/BP/2026/4412',
        docTitle: 'Nairobi City County Single Business Permit',
        uploadedAt: '2026-03-01',
        verificationStatus: 'verified',
        verifiedBy: 'USR-005',
      },
    ],
    createdAt: '2026-03-01',
  },
  {
    id: 'CUS-2026-000003',
    customerNumber: 'CUS-2026-000003',
    type: 'business',
    fullName: 'Peter Mwangi Njoroge',
    idNumber: '31049281',
    kraPin: 'P051829304M',
    dateOfBirth: '1992-04-12',
    gender: 'male',
    phone: '+254 734 778 899',
    email: 'peter.mwangi@swiftagro.co.ke',
    address: 'Section 58, Near Shell Station',
    county: 'Nakuru',
    town: 'Nakuru',
    occupation: 'Agri-Equipment Contractor',
    employer: 'Self Employed',
    monthlyIncome: 240000,
    monthlyExpenses: 125000,
    businessName: 'Swift Agro Tractors & Machinery',
    businessRegistrationNumber: 'BN/2021/44781',
    nextOfKinName: 'Lucy Nyambura Mwangi',
    nextOfKinPhone: '+254 735 889 900',
    nextOfKinRelation: 'Sister',
    status: 'active',
    riskClassification: 'medium',
    branchId: 'BR-004',
    creditScore: 680,
    notes: 'Operates agricultural tractors and transport pickups in the Rift Valley.',
    documents: [
      {
        id: 'DOC-06',
        docType: 'national_id',
        docNumber: '31049281',
        docTitle: 'National ID Card',
        uploadedAt: '2026-03-10',
        verificationStatus: 'verified',
        verifiedBy: 'USR-004',
      },
    ],
    createdAt: '2026-03-10',
  },
  {
    id: 'CUS-2026-000004',
    customerNumber: 'CUS-2026-000004',
    type: 'company',
    fullName: 'Apex Hardware & Glass Distributors Ltd',
    idNumber: 'CPR/2016/22819',
    kraPin: 'P051283948K',
    phone: '+254 710 990 011',
    email: 'finance@apexhardware.co.ke',
    address: 'Industrial Area, Commercial Street, GoDown 14',
    county: 'Nairobi',
    town: 'Nairobi',
    occupation: 'Commercial Building Materials',
    employer: 'Corporate Entity',
    monthlyIncome: 1200000,
    monthlyExpenses: 680000,
    businessName: 'Apex Hardware & Glass Distributors Ltd',
    businessRegistrationNumber: 'CPR/2016/22819',
    nextOfKinName: 'Hassan Ali Noor (Managing Director)',
    nextOfKinPhone: '+254 722 881 122',
    nextOfKinRelation: 'Principal Shareholder',
    status: 'active',
    riskClassification: 'low',
    branchId: 'BR-001',
    creditScore: 810,
    notes: 'Established commercial distributor borrowing against industrial machinery and prime commercial plots.',
    documents: [],
    createdAt: '2026-01-20',
  },
];

export const SEED_ASSETS: Asset[] = [
  {
    id: 'AST-2026-000001',
    category: 'motor_vehicle',
    customerId: 'CUS-2026-000001',
    ownerName: 'John Kamau Mwangi',
    titleOrName: 'Toyota Probox Van 2018 (KCA 123A)',
    description: 'White Toyota Probox 1.5L DX, 2018 model in pristine operating condition. Clean upholstery, original paint.',
    location: 'Ruaka, Kiambu County',
    condition: 'excellent',
    marketValue: 1250000,
    forcedSaleValue: 950000,
    purchaseValue: 1350000,
    acquisitionDate: '2022-04-10',
    status: 'active_collateral',
    branchId: 'BR-001',
    photos: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
    ],
    vehicleDetails: {
      registrationNumber: 'KCA 123A',
      make: 'Toyota',
      model: 'Probox',
      year: 2018,
      color: 'White',
      chassisVin: 'NCP160-0048192',
      engineNumber: '1NZ-FE-829104',
      logbookNumber: 'LOG-KCA123A-2018',
      mileageKm: 84500,
      fuelType: 'petrol',
      transmission: 'automatic',
      vehicleCategory: 'commercial',
      insuranceCompany: 'Jubilee Insurance Kenya',
      insurancePolicyNumber: 'POL-JUB-2026-9921',
      insuranceExpiry: '2027-02-28',
      logbookSubmitted: true,
      idOwnerVerified: true,
      ownershipCheckedNtsa: true,
      vehicleDetailsChecked: true,
      valuationCompleted: true,
      insuranceChecked: true,
      existingChargesChecked: true,
      finalVerificationPassed: true,
    },
    createdAt: '2026-02-18',
  },
  {
    id: 'AST-2026-000002',
    category: 'motor_vehicle',
    customerId: 'CUS-2026-000002',
    ownerName: 'Mary Wanjiku Kariuki',
    titleOrName: 'Toyota Fielder Station Wagon 2019 (KDG 892W)',
    description: 'Silver Metallic Toyota Corolla Fielder 1.5X, automatic, keyless entry, alloy rims.',
    location: 'Kileleshwa, Nairobi',
    condition: 'excellent',
    marketValue: 1650000,
    forcedSaleValue: 1250000,
    purchaseValue: 1780000,
    acquisitionDate: '2023-01-15',
    status: 'active_collateral',
    branchId: 'BR-001',
    photos: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80',
    ],
    vehicleDetails: {
      registrationNumber: 'KDG 892W',
      make: 'Toyota',
      model: 'Fielder',
      year: 2019,
      color: 'Silver Metallic',
      chassisVin: 'NRE161-0029148',
      engineNumber: '2NR-FKE-119284',
      logbookNumber: 'LOG-KDG892W-2019',
      mileageKm: 62000,
      fuelType: 'petrol',
      transmission: 'automatic',
      vehicleCategory: 'sedan',
      insuranceCompany: 'Britam General Insurance',
      insurancePolicyNumber: 'BRIT-MTR-88319',
      insuranceExpiry: '2027-04-15',
      logbookSubmitted: true,
      idOwnerVerified: true,
      ownershipCheckedNtsa: true,
      vehicleDetailsChecked: true,
      valuationCompleted: true,
      insuranceChecked: true,
      existingChargesChecked: true,
      finalVerificationPassed: true,
    },
    createdAt: '2026-03-02',
  },
  {
    id: 'AST-2026-000003',
    category: 'residential_property',
    customerId: 'CUS-2026-000002',
    ownerName: 'Mary Wanjiku Kariuki',
    titleOrName: '4-Bedroom Townhouse on 1/8 Acre (Title No. KIAMBU/MUGUGA/4812)',
    description: 'Executive modern 4-bedroom maisonette all en-suite with perimeter boundary wall, electric fence, and borehole water connection.',
    location: 'Muguga, Kiambu County',
    condition: 'excellent',
    marketValue: 18500000,
    forcedSaleValue: 14000000,
    purchaseValue: 15000000,
    acquisitionDate: '2021-08-20',
    status: 'active_collateral',
    branchId: 'BR-001',
    photos: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    ],
    propertyDetails: {
      propertyType: 'house',
      titleNumber: 'TITLE-KBU-4812',
      parcelLrNumber: 'KIAMBU/MUGUGA/4812',
      county: 'Kiambu',
      subCounty: 'Kabete',
      town: 'Muguga / Kikuyu',
      areaLocation: 'Sigona View Estate',
      sizeAcreage: '0.05 Ha (1/8th Acre)',
      tenure: 'freehold',
      occupancyStatus: 'owner_occupied',
      existingEncumbrances: 'None. Certified official search clean.',
      registrySearchRef: 'SRCH/KBU/2026/9931',
      titleVerificationPassed: true,
      ratesClearancePassed: true,
      landControlBoardConsentPassed: true,
    },
    createdAt: '2026-03-05',
  },
  {
    id: 'AST-2026-000004',
    category: 'commercial_property',
    customerId: 'CUS-2026-000004',
    ownerName: 'Apex Hardware & Glass Distributors Ltd',
    titleOrName: 'Commercial Plot in Kilimani (LR No. 209/18420)',
    description: 'Prime 0.25-acre commercial redevelopment parcel touching Argwings Kodhek Road. Ideal for multi-story mixed use.',
    location: 'Kilimani, Nairobi',
    condition: 'good',
    marketValue: 42000000,
    forcedSaleValue: 32000000,
    purchaseValue: 35000000,
    acquisitionDate: '2019-11-12',
    status: 'active_collateral',
    branchId: 'BR-001',
    photos: [
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    ],
    propertyDetails: {
      propertyType: 'commercial',
      titleNumber: 'TITLE-NRB-209-18420',
      parcelLrNumber: 'LR No. 209/18420',
      county: 'Nairobi',
      subCounty: 'Dagoretti North',
      town: 'Kilimani',
      areaLocation: 'Argwings Kodhek Road',
      sizeAcreage: '0.25 Acre (0.101 Ha)',
      tenure: 'leasehold',
      occupancyStatus: 'tenanted',
      existingEncumbrances: 'First legal charge registered in favor of Davetech ERP',
      registrySearchRef: 'SRCH/NRB/LANDS/2026/18420',
      titleVerificationPassed: true,
      ratesClearancePassed: true,
      landControlBoardConsentPassed: true,
    },
    createdAt: '2026-01-25',
  },
  {
    id: 'AST-2026-000005',
    category: 'machinery',
    customerId: 'CUS-2026-000003',
    ownerName: 'Peter Mwangi Njoroge',
    titleOrName: 'Caterpillar 150 kVA Soundproof Industrial Generator',
    description: 'Heavy duty diesel standby generator set, Perkins diesel engine, brushless alternator, sound-attenuated acoustic canopy.',
    location: 'Industrial Area, Nakuru',
    condition: 'good',
    marketValue: 2800000,
    forcedSaleValue: 2100000,
    purchaseValue: 3200000,
    acquisitionDate: '2023-06-15',
    status: 'active_collateral',
    branchId: 'BR-004',
    photos: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    ],
    notes: 'Mounted on concrete plinth. Serial No: CAT-150-KEN-88310. Regularly serviced with full maintenance log.',
    createdAt: '2026-03-12',
  },
  {
    id: 'AST-2026-000006',
    category: 'motor_vehicle',
    customerId: 'CUS-2026-000003',
    ownerName: 'Peter Mwangi Njoroge',
    titleOrName: 'Isuzu D-Max Double Cab 2017 (KBZ 445T)',
    description: '3.0L Diesel 4WD pickup, bullbar, winch, canopy, high suspension for agricultural field monitoring.',
    location: 'Nakuru Town',
    condition: 'fair',
    marketValue: 2400000,
    forcedSaleValue: 1800000,
    purchaseValue: 2600000,
    acquisitionDate: '2020-05-18',
    status: 'under_recovery',
    branchId: 'BR-004',
    photos: [
      'https://images.unsplash.com/photo-1551830820-330a71b99659?auto=format&fit=crop&w=800&q=80',
    ],
    vehicleDetails: {
      registrationNumber: 'KBZ 445T',
      make: 'Isuzu',
      model: 'D-Max',
      year: 2017,
      color: 'Navy Blue',
      chassisVin: 'MP1TFR85H-99218',
      engineNumber: '4JJ1-TC-77219',
      logbookNumber: 'LOG-KBZ445T-2017',
      mileageKm: 148000,
      fuelType: 'diesel',
      transmission: 'manual',
      vehicleCategory: 'pickup',
      insuranceCompany: 'APA Insurance Ltd',
      insurancePolicyNumber: 'APA-COM-77821',
      insuranceExpiry: '2026-11-30',
      logbookSubmitted: true,
      idOwnerVerified: true,
      ownershipCheckedNtsa: true,
      vehicleDetailsChecked: true,
      valuationCompleted: true,
      insuranceChecked: true,
      existingChargesChecked: true,
      finalVerificationPassed: true,
    },
    createdAt: '2026-02-10',
  },
  {
    id: 'AST-2026-000007',
    category: 'household_goods',
    customerId: 'CUS-2026-000001',
    ownerName: 'John Kamau Mwangi',
    titleOrName: 'Sony Bravia 55" 4K UHD Smart Android TV',
    description: '55-inch 4K HDR Smart Google TV with Triluminos Pro Display, Dolby Atmos Audio, 4 HDMI ports, voice remote control and heavy-duty swivel wall bracket.',
    location: 'Nairobi Main Branch Vault (Locker B-02)',
    condition: 'excellent',
    marketValue: 75000,
    forcedSaleValue: 52000,
    purchaseValue: 89000,
    acquisitionDate: '2024-04-10',
    status: 'active_collateral',
    branchId: 'BR-001',
    photos: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
    ],
    itemDetails: {
      itemType: 'tv',
      brand: 'Sony',
      model: 'Bravia KD-55X80K',
      serialNumber: 'SN-SONY-55-98312A',
      color: 'Titanium Black',
      screenSize: '55 Inch Smart 4K UHD',
      condition: 'mint',
      accessoriesIncluded: ['Smart Voice Remote', 'Power Cable', 'Original Table Stands', 'Wall Bracket'],
      custodyType: 'in_branch_vault',
      custodyLocation: 'Nairobi CBD Branch Vault Storage Rack B-02',
      originalReceiptOrReceiptProof: true,
    },
    notes: 'Zero dead pixels, physical inspection passed, remote and all cables sealed in vault.',
    createdAt: '2026-02-28',
  },
  {
    id: 'AST-2026-000008',
    category: 'household_goods',
    customerId: 'CUS-2026-000003',
    ownerName: 'Peter Mwangi Njoroge',
    titleOrName: 'Tagwood 5.1ch High-Bass Multimedia Woofer System',
    description: 'Tagwood 250W RMS surround sound system with 8-inch active subwoofer, 5 satellite speakers, Bluetooth 5.0, USB/SD playback, FM tuner and master remote.',
    location: 'Nakuru Branch Safe Custody #03',
    condition: 'good',
    marketValue: 28000,
    forcedSaleValue: 19500,
    purchaseValue: 34000,
    acquisitionDate: '2023-11-05',
    status: 'active_collateral',
    branchId: 'BR-004',
    photos: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    ],
    itemDetails: {
      itemType: 'woofer',
      brand: 'Tagwood',
      model: 'TAG-5100-PRO Bass',
      serialNumber: 'SN-TGW-51-44910X',
      color: 'Black with Red Accents',
      powerWattage: '250W RMS / 20,000W PMPO',
      condition: 'good',
      accessoriesIncluded: ['5 Satellite Speakers', 'RCA to AUX Cables', 'Remote Control', 'FM Antenna'],
      custodyType: 'in_branch_vault',
      custodyLocation: 'Nakuru Branch Electronics Safe Room',
      originalReceiptOrReceiptProof: true,
    },
    notes: 'Sound output tested across all 5 channels with clear bass response.',
    createdAt: '2026-03-01',
  },
  {
    id: 'AST-2026-000009',
    category: 'furniture',
    customerId: 'CUS-2026-000002',
    ownerName: 'Grace Wanjiku Kariuki',
    titleOrName: 'Executive 7-Seater Chesterfield Living Room Sofa Set',
    description: 'Complete 7-seater luxury tufted living room suite (3-seater + 2-seater + 2 single recliners) crafted from solid Meru oak framework and high-density foam.',
    location: 'Borrower Residence (Pledged under Chattels Transfer Act with Inspection Tag DT-CHT-009)',
    condition: 'excellent',
    marketValue: 160000,
    forcedSaleValue: 110000,
    purchaseValue: 195000,
    acquisitionDate: '2024-01-20',
    status: 'active_collateral',
    branchId: 'BR-001',
    photos: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
    ],
    itemDetails: {
      itemType: 'chair',
      brand: 'Victoria Courts Custom',
      model: 'Chesterfield Royal 7-Piece',
      serialNumber: 'TAG-CHT-FURN-009',
      color: 'Deep Navy Blue Fabric',
      material: 'Meru Oak Hardwood & Heavy Stain-Resistant Velvet Fabric',
      condition: 'mint',
      accessoriesIncluded: ['6 Accent Throw Cushions', 'Manufacturer Warranty Card'],
      custodyType: 'held_by_borrower_chattel',
      custodyLocation: 'Borrower Residence - Ruaka Ridge Estate House 42B',
      originalReceiptOrReceiptProof: true,
    },
    notes: 'Pledged under Chattels Transfer Act Cap 28. Inspected and tagged on-site with monthly spot-check agreement.',
    createdAt: '2026-03-04',
  },
  {
    id: 'AST-2026-000010',
    category: 'household_goods',
    customerId: 'CUS-2026-000001',
    ownerName: 'John Kamau Mwangi',
    titleOrName: 'Samsung 260L Double Door No-Frost Refrigerator',
    description: 'Samsung Digital Inverter Top Mount Freezer Refrigerator with all-around cooling, deodorizing filter, toughened glass shelves, and 10-year compressor warranty.',
    location: 'Nairobi Main Branch Vault (Appliance Bay A-01)',
    condition: 'excellent',
    marketValue: 58000,
    forcedSaleValue: 40000,
    purchaseValue: 69000,
    acquisitionDate: '2024-06-12',
    status: 'available',
    branchId: 'BR-001',
    photos: [
      'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
    ],
    itemDetails: {
      itemType: 'fridge',
      brand: 'Samsung',
      model: 'RT28K3032GS/KE',
      serialNumber: 'SN-SMG-260-88192',
      color: 'Silver Metallic',
      condition: 'brand_new',
      accessoriesIncluded: ['Ice Tray Box', 'Egg Rack', 'Original Manual & Warranty Card'],
      custodyType: 'in_branch_vault',
      custodyLocation: 'Nairobi Main Branch Appliance Bay A-01',
      originalReceiptOrReceiptProof: true,
    },
    notes: 'Fully functional, pristine condition with zero dents or scratches.',
    createdAt: '2026-03-08',
  },
  {
    id: 'AST-2026-000011',
    category: 'electronics',
    customerId: 'CUS-2026-000003',
    ownerName: 'Peter Mwangi Njoroge',
    titleOrName: 'HP EliteBook 840 G8 Core i7 16GB / 512GB SSD Laptop',
    description: '11th Gen Intel Core i7-1165G7, 16GB DDR4 RAM, 512GB NVMe M.2 SSD, 14-inch Full HD IPS Anti-Glare Display, Backlit Keyboard, Fingerprint Reader, Windows 11 Pro.',
    location: 'Nairobi Main Branch Strongroom (Electronics Safe B-04)',
    condition: 'excellent',
    marketValue: 82000,
    forcedSaleValue: 58000,
    purchaseValue: 98000,
    acquisitionDate: '2024-02-18',
    status: 'available',
    branchId: 'BR-001',
    photos: [
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=80',
    ],
    itemDetails: {
      itemType: 'laptop',
      brand: 'HP',
      model: 'EliteBook 840 G8',
      serialNumber: 'CND14889XY',
      color: 'Silver Aluminum',
      condition: 'mint',
      accessoriesIncluded: ['Original 65W USB-C Charger', 'Padded HP Carry Bag'],
      custodyType: 'in_branch_vault',
      custodyLocation: 'Electronics Vault Locker B-04',
      originalReceiptOrReceiptProof: true,
    },
    notes: 'Battery health tested at 94%, diagnostics passed with zero hardware faults.',
    createdAt: '2026-03-09',
  },
];

export const SEED_COLLATERALS: Collateral[] = [
  {
    id: 'COL-2026-000145',
    customerId: 'CUS-2026-000001',
    assetId: 'AST-2026-000001',
    activeLoanId: 'LOG-2026-000001',
    collateralType: 'motor_vehicle',
    description: 'Motor Vehicle Logbook: Toyota Probox KCA 123A',
    marketValue: 1250000,
    forcedSaleValue: 950000,
    approvedCollateralValue: 950000,
    loanToValuePct: 70,
    eligibleCollateralValue: 665000,
    status: 'active',
    custodian: 'Esther Njeri (Custody Officer)',
    storageLocation: 'Head Office Strongroom Safe Box #04',
    registrationSecurityRef: 'NTSA/CAVEAT/2026/88319',
    verificationStatus: 'verified',
    verifiedBy: 'USR-006',
    verifiedAt: '2026-02-20',
    pledgeDate: '2026-02-22',
    branchId: 'BR-001',
    documents: [
      {
        id: 'CDOC-01',
        name: 'Original Logbook KCA 123A',
        type: 'logbook',
        status: 'verified',
        verifiedBy: 'USR-009',
        verifiedAt: '2026-02-21',
      },
      {
        id: 'CDOC-02',
        name: 'Professional Valuation Report (Regent Valuers)',
        type: 'valuation_report',
        status: 'verified',
        verifiedBy: 'USR-006',
        verifiedAt: '2026-02-20',
      },
      {
        id: 'CDOC-03',
        name: 'Signed Chattels Transfer & Security Agreement',
        type: 'security_agreement',
        status: 'verified',
        verifiedBy: 'USR-003',
        verifiedAt: '2026-02-22',
      },
    ],
    notes: 'NTSA joint ownership caveat registered. Spare keys deposited in custody safe.',
    createdAt: '2026-02-19',
  },
  {
    id: 'COL-2026-000146',
    customerId: 'CUS-2026-000002',
    assetId: 'AST-2026-000003',
    activeLoanId: 'PROP-2026-000002',
    collateralType: 'residential_property',
    description: 'Title Deed: KIAMBU/MUGUGA/4812 (Maisonette)',
    marketValue: 18500000,
    forcedSaleValue: 14000000,
    approvedCollateralValue: 14000000,
    loanToValuePct: 60,
    eligibleCollateralValue: 8400000,
    status: 'active',
    custodian: 'Esther Njeri (Custody Officer)',
    storageLocation: 'Head Office Deed Vault #12',
    registrationSecurityRef: 'REG/LANDS/KBU/CHG/2026/4812',
    verificationStatus: 'verified',
    verifiedBy: 'USR-006',
    verifiedAt: '2026-03-06',
    pledgeDate: '2026-03-08',
    branchId: 'BR-001',
    documents: [
      {
        id: 'CDOC-04',
        name: 'Original Title Deed KIAMBU/MUGUGA/4812',
        type: 'title_deed',
        status: 'verified',
        verifiedBy: 'USR-009',
        verifiedAt: '2026-03-07',
      },
      {
        id: 'CDOC-05',
        name: 'Certified Official Land Registry Search',
        type: 'search_certificate',
        status: 'verified',
        verifiedBy: 'USR-006',
        verifiedAt: '2026-03-06',
      },
    ],
    notes: 'Charge registered at Kiambu Lands Registry. Valuation done by Knight Frank Kenya.',
    createdAt: '2026-03-06',
  },
  {
    id: 'COL-2026-000147',
    customerId: 'CUS-2026-000003',
    assetId: 'AST-2026-000006',
    activeLoanId: 'LOG-2026-000003',
    collateralType: 'motor_vehicle',
    description: 'Motor Vehicle Logbook: Isuzu D-Max KBZ 445T',
    marketValue: 2400000,
    forcedSaleValue: 1800000,
    approvedCollateralValue: 1800000,
    loanToValuePct: 70,
    eligibleCollateralValue: 1260000,
    status: 'recovery',
    custodian: 'Michael Wafula (Recovery Officer)',
    storageLocation: 'Nakuru Secured Impound Yard #02',
    registrationSecurityRef: 'NTSA/CHG/2026/445T',
    verificationStatus: 'verified',
    verifiedBy: 'USR-006',
    verifiedAt: '2026-02-12',
    pledgeDate: '2026-02-14',
    branchId: 'BR-004',
    documents: [
      {
        id: 'CDOC-06',
        name: 'Original Logbook KBZ 445T',
        type: 'logbook',
        status: 'verified',
        verifiedBy: 'USR-009',
        verifiedAt: '2026-02-13',
      },
    ],
    notes: 'Borrower defaulted for 68 days. Vehicle tracked and safely stored at Nakuru yard.',
    createdAt: '2026-02-11',
  },
  {
    id: 'COL-2026-000148',
    customerId: 'CUS-2026-000001',
    assetId: 'AST-2026-000007',
    activeLoanId: 'ITM-2026-000014',
    collateralType: 'household_goods',
    description: 'Pledged Electronics: Sony Bravia 55" 4K Smart Android TV (SN: SN-SONY-55-98312A)',
    marketValue: 75000,
    forcedSaleValue: 52000,
    approvedCollateralValue: 52000,
    loanToValuePct: 70,
    eligibleCollateralValue: 36400,
    status: 'active',
    custodian: 'Esther Njeri (Custody Officer)',
    storageLocation: 'Nairobi CBD Branch Vault Storage Rack B-02',
    registrationSecurityRef: 'DT/CHT/2026/ELC-007',
    verificationStatus: 'verified',
    verifiedBy: 'USR-006',
    verifiedAt: '2026-03-01',
    pledgeDate: '2026-03-02',
    branchId: 'BR-001',
    documents: [
      {
        id: 'CDOC-07',
        name: 'Physical Electronics Inspection & Condition Certificate',
        type: 'valuation_report',
        status: 'verified',
        verifiedBy: 'USR-006',
        verifiedAt: '2026-03-01',
      },
      {
        id: 'CDOC-08',
        name: 'Signed Item Chattel Mortgage & Pledge Agreement',
        type: 'security_agreement',
        status: 'verified',
        verifiedBy: 'USR-003',
        verifiedAt: '2026-03-02',
      },
    ],
    notes: 'TV in branch custody with all accessories. Covered under Davetech vault fire & theft policy.',
    createdAt: '2026-03-01',
  },
  {
    id: 'COL-2026-000149',
    customerId: 'CUS-2026-000003',
    assetId: 'AST-2026-000008',
    activeLoanId: 'ITM-2026-000015',
    collateralType: 'household_goods',
    description: 'Pledged Audio Equipment: Tagwood 5.1ch High-Bass Multimedia Woofer (SN: SN-TGW-51-44910X)',
    marketValue: 28000,
    forcedSaleValue: 19500,
    approvedCollateralValue: 19500,
    loanToValuePct: 65,
    eligibleCollateralValue: 12675,
    status: 'active',
    custodian: 'Michael Wafula (Custody Officer)',
    storageLocation: 'Nakuru Branch Electronics Safe Room',
    registrationSecurityRef: 'DT/CHT/2026/ELC-008',
    verificationStatus: 'verified',
    verifiedBy: 'USR-006',
    verifiedAt: '2026-03-02',
    pledgeDate: '2026-03-03',
    branchId: 'BR-004',
    documents: [
      {
        id: 'CDOC-09',
        name: 'Audio Diagnostics & Speaker Channel Check Sheet',
        type: 'valuation_report',
        status: 'verified',
        verifiedBy: 'USR-006',
        verifiedAt: '2026-03-02',
      },
    ],
    notes: 'Tested functional, master remote packaged in bubble wrap.',
    createdAt: '2026-03-02',
  },
  {
    id: 'COL-2026-000150',
    customerId: 'CUS-2026-000002',
    assetId: 'AST-2026-000009',
    activeLoanId: 'ITM-2026-000016',
    collateralType: 'furniture',
    description: 'Pledged Furniture: Executive 7-Seater Chesterfield Living Room Sofa Suite (Tag DT-CHT-009)',
    marketValue: 160000,
    forcedSaleValue: 110000,
    approvedCollateralValue: 110000,
    loanToValuePct: 60,
    eligibleCollateralValue: 66000,
    status: 'active',
    custodian: 'Esther Njeri (Field Inspection Officer)',
    storageLocation: 'Borrower Residence under Chattels Mortgage Seal',
    registrationSecurityRef: 'REG/CHATTELS/CAP28/2026/FRN-009',
    verificationStatus: 'verified',
    verifiedBy: 'USR-004',
    verifiedAt: '2026-03-05',
    pledgeDate: '2026-03-06',
    branchId: 'BR-001',
    documents: [
      {
        id: 'CDOC-10',
        name: 'In-Situ Furniture Verification & Chattels Cap 28 Deed',
        type: 'security_agreement',
        status: 'verified',
        verifiedBy: 'USR-004',
        verifiedAt: '2026-03-05',
      },
    ],
    notes: 'Borrower retains physical possession with strict covenants against relocation without written lender sanction.',
    createdAt: '2026-03-05',
  },
];

export const SEED_VALUATIONS: Valuation[] = [
  {
    id: 'VAL-2026-000001',
    assetId: 'AST-2026-000001',
    customerId: 'CUS-2026-000001',
    valuerName: 'Eng. Samuel Njoroge',
    valuerCompany: 'Regent Automobile Valuers & Assessors',
    valuationDate: '2026-02-20',
    marketValue: 1250000,
    forcedSaleValue: 950000,
    recommendedLendingValue: 665000,
    status: 'approved',
    approvedBy: 'USR-003',
    photos: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
    ],
    notes: 'Engine running smoothly, zero chassis deformation, clean interior. Approved for 70% FSV lending.',
    createdAt: '2026-02-20',
  },
  {
    id: 'VAL-2026-000002',
    assetId: 'AST-2026-000003',
    customerId: 'CUS-2026-000002',
    valuerName: 'David Makau (MISK)',
    valuerCompany: 'Knight Frank Kenya Ltd',
    valuationDate: '2026-03-06',
    marketValue: 18500000,
    forcedSaleValue: 14000000,
    recommendedLendingValue: 8400000,
    status: 'approved',
    approvedBy: 'USR-003',
    photos: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    ],
    notes: 'Prime residential locality with fast appreciation. Freehold tenure verified.',
    createdAt: '2026-03-06',
  },
];

export const SEED_LOAN_PRODUCTS: LoanProduct[] = [
  {
    id: 'LP-001',
    name: 'Logbook Loan (Movable Vehicle)',
    code: 'LOGBOOK-SEC',
    description: 'Secured against passenger and commercial motor vehicle logbooks with NTSA security caveat.',
    minAmount: 100000,
    maxAmount: 5000000,
    interestRatePerMonth: 3.5,
    interestMethod: 'flat_rate',
    processingFeePct: 3.0,
    insuranceFeePct: 1.5,
    legalFeePct: 1.0,
    penaltyRatePerMonth: 5.0,
    gracePeriodDays: 5,
    minDurationMonths: 3,
    maxDurationMonths: 24,
    repaymentFrequency: 'monthly',
    maxLtvPct: 70,
    requiredCollateralCategory: ['motor_vehicle'],
    approvalLevels: 2,
    status: 'active',
  },
  {
    id: 'LP-002',
    name: 'Title Deed & Property Secured Loan',
    code: 'TITLE-PROP',
    description: 'Secured by residential, commercial, or agricultural land title deeds with registered legal charge.',
    minAmount: 500000,
    maxAmount: 50000000,
    interestRatePerMonth: 2.2,
    interestMethod: 'reducing_balance',
    processingFeePct: 2.5,
    insuranceFeePct: 1.0,
    legalFeePct: 2.0,
    penaltyRatePerMonth: 4.0,
    gracePeriodDays: 7,
    minDurationMonths: 6,
    maxDurationMonths: 48,
    repaymentFrequency: 'monthly',
    maxLtvPct: 60,
    requiredCollateralCategory: ['residential_property', 'commercial_property', 'land'],
    approvalLevels: 3,
    status: 'active',
  },
  {
    id: 'LP-003',
    name: 'Industrial Machinery & Equipment Finance',
    code: 'MACH-FIN',
    description: 'Secured by manufacturing machinery, commercial generators, construction plant, and yellow metal.',
    minAmount: 300000,
    maxAmount: 20000000,
    interestRatePerMonth: 2.8,
    interestMethod: 'reducing_balance',
    processingFeePct: 2.5,
    insuranceFeePct: 2.0,
    legalFeePct: 1.5,
    penaltyRatePerMonth: 5.0,
    gracePeriodDays: 5,
    minDurationMonths: 6,
    maxDurationMonths: 36,
    repaymentFrequency: 'monthly',
    maxLtvPct: 65,
    requiredCollateralCategory: ['machinery', 'equipment'],
    approvalLevels: 3,
    status: 'active',
  },
  {
    id: 'LP-004',
    name: 'Emergency 30-Day Logbook Advance',
    code: 'EMERG-LOG',
    description: 'Rapid turnaround emergency liquidity backed by vehicle logbook for working capital emergencies.',
    minAmount: 50000,
    maxAmount: 1000000,
    interestRatePerMonth: 4.5,
    interestMethod: 'flat_rate',
    processingFeePct: 4.0,
    insuranceFeePct: 1.0,
    legalFeePct: 0.5,
    penaltyRatePerMonth: 8.0,
    gracePeriodDays: 3,
    minDurationMonths: 1,
    maxDurationMonths: 3,
    repaymentFrequency: 'monthly',
    maxLtvPct: 60,
    requiredCollateralCategory: ['motor_vehicle'],
    approvalLevels: 1,
    status: 'active',
  },
  {
    id: 'LP-005',
    name: 'Household Goods & Electronics Asset Loan',
    code: 'HOUSEHOLD-ITEM-LOAN',
    description: 'Instant collateralized micro-financing against Smart TVs, audio woofers, living room chairs/sofas, refrigerators, microwaves, and laptops.',
    minAmount: 5000,
    maxAmount: 500000,
    interestRatePerMonth: 4.0,
    interestMethod: 'flat_rate',
    processingFeePct: 3.0,
    insuranceFeePct: 1.0,
    legalFeePct: 0.5,
    penaltyRatePerMonth: 5.0,
    gracePeriodDays: 5,
    minDurationMonths: 1,
    maxDurationMonths: 12,
    repaymentFrequency: 'monthly',
    maxLtvPct: 70,
    requiredCollateralCategory: ['household_goods', 'electronics', 'furniture'],
    approvalLevels: 1,
    status: 'active',
  },
];

export const SEED_APPLICATIONS: LoanApplication[] = [
  {
    id: 'APP-2026-000001',
    applicationNumber: 'APP-2026-000001',
    customerId: 'CUS-2026-000001',
    loanProductId: 'LP-001',
    requestedAmount: 600000,
    proposedDurationMonths: 12,
    purpose: 'Expansion of spare parts stock and logistics working capital',
    collateralId: 'COL-2026-000145',
    repaymentFrequency: 'monthly',
    loanOfficerId: 'USR-004',
    branchId: 'BR-001',
    status: 'disbursed',
    monthlyDeclaredIncome: 320000,
    monthlyDeclaredExpenses: 110000,
    existingLiabilities: 30000,
    statusHistory: [
      {
        status: 'submitted',
        changedBy: 'USR-004',
        changedAt: '2026-02-18 10:00',
        comment: 'Application submitted with verified logbook and KCB statement.',
      },
      {
        status: 'credit_assessment',
        changedBy: 'USR-005',
        changedAt: '2026-02-19 14:00',
        comment: 'Income verified. DSR is healthy at 28%. Collateral LTV is 63%.',
      },
      {
        status: 'approved',
        changedBy: 'USR-003',
        changedAt: '2026-02-21 11:30',
        comment: 'Branch Manager approved full requested amount of KES 600,000.',
      },
      {
        status: 'disbursed',
        changedBy: 'USR-007',
        changedAt: '2026-02-22 09:15',
        comment: 'Funds disbursed to customer KCB account via EFT.',
      },
    ],
    createdAt: '2026-02-18',
  },
  {
    id: 'APP-2026-000002',
    applicationNumber: 'APP-2026-000002',
    customerId: 'CUS-2026-000002',
    loanProductId: 'LP-002',
    requestedAmount: 5000000,
    proposedDurationMonths: 24,
    purpose: 'Construction of commercial retail warehouse in Thika',
    collateralId: 'COL-2026-000146',
    repaymentFrequency: 'monthly',
    loanOfficerId: 'USR-004',
    branchId: 'BR-001',
    status: 'disbursed',
    monthlyDeclaredIncome: 450000,
    monthlyDeclaredExpenses: 160000,
    existingLiabilities: 45000,
    statusHistory: [
      {
        status: 'submitted',
        changedBy: 'USR-004',
        changedAt: '2026-03-02 09:30',
        comment: 'Application submitted with original title deed and valuation report.',
      },
      {
        status: 'credit_assessment',
        changedBy: 'USR-005',
        changedAt: '2026-03-04 15:00',
        comment: 'DSR acceptable. Excellent property coverage with 35% LTV.',
      },
      {
        status: 'approved',
        changedBy: 'USR-001',
        changedAt: '2026-03-07 16:20',
        comment: 'Executive committee approval given for KES 5,000,000.',
      },
      {
        status: 'disbursed',
        changedBy: 'USR-007',
        changedAt: '2026-03-08 11:00',
        comment: 'Disbursement completed to Equity Bank Account.',
      },
    ],
    createdAt: '2026-03-02',
  },
  {
    id: 'APP-2026-000003',
    applicationNumber: 'APP-2026-000003',
    customerId: 'CUS-2026-000004',
    loanProductId: 'LP-002',
    requestedAmount: 12000000,
    proposedDurationMonths: 36,
    purpose: 'Bulk importation of toughened glass and structural aluminum from Turkey',
    collateralId: 'COL-2026-000148',
    repaymentFrequency: 'monthly',
    loanOfficerId: 'USR-004',
    branchId: 'BR-001',
    status: 'pending_approval',
    monthlyDeclaredIncome: 1200000,
    monthlyDeclaredExpenses: 680000,
    existingLiabilities: 120000,
    statusHistory: [
      {
        status: 'submitted',
        changedBy: 'USR-004',
        changedAt: '2026-09-10 11:00',
        comment: 'Corporate application with audited accounts and Kilimani parcel.',
      },
      {
        status: 'credit_assessment',
        changedBy: 'USR-005',
        changedAt: '2026-09-12 14:30',
        comment: 'Credit Officer recommends approval. Prime plot value KES 42M.',
      },
    ],
    createdAt: '2026-09-10',
  },
];

// Helper to calculate initial loan schedules
const log1Calc = LoanEngine.calculateLoan({
  principal: 600000,
  interestRatePerMonth: 3.5,
  durationMonths: 12,
  interestMethod: 'flat_rate',
  repaymentFrequency: 'monthly',
  processingFeePct: 3.0,
  insuranceFeePct: 1.5,
  startDate: new Date('2026-02-22'),
});

// Simulate partial payments on loan 1
const updatedSchedule1 = log1Calc.schedule.map((item, idx) => {
  if (idx < 6) {
    return {
      ...item,
      principalPaid: item.principalDue,
      interestPaid: item.interestDue,
      feesPaid: item.feesDue,
      totalPaid: item.totalInstallment,
      status: 'paid' as const,
    };
  }
  return item;
});

const prop2Calc = LoanEngine.calculateLoan({
  principal: 5000000,
  interestRatePerMonth: 2.2,
  durationMonths: 24,
  interestMethod: 'reducing_balance',
  repaymentFrequency: 'monthly',
  processingFeePct: 2.5,
  insuranceFeePct: 1.0,
  startDate: new Date('2026-03-08'),
});

const updatedSchedule2 = prop2Calc.schedule.map((item, idx) => {
  if (idx < 5) {
    return {
      ...item,
      principalPaid: item.principalDue,
      interestPaid: item.interestDue,
      feesPaid: item.feesDue,
      totalPaid: item.totalInstallment,
      status: 'paid' as const,
    };
  }
  return item;
});

// Overdue loan for Nakuru branch
const overdueLoanCalc = LoanEngine.calculateLoan({
  principal: 1000000,
  interestRatePerMonth: 3.5,
  durationMonths: 12,
  interestMethod: 'flat_rate',
  repaymentFrequency: 'monthly',
  processingFeePct: 3.0,
  insuranceFeePct: 1.5,
  startDate: new Date('2026-02-14'),
});

const updatedOverdueSchedule = overdueLoanCalc.schedule.map((item, idx) => {
  if (idx === 0) {
    return {
      ...item,
      principalPaid: item.principalDue,
      interestPaid: item.interestDue,
      feesPaid: item.feesDue,
      totalPaid: item.totalInstallment,
      status: 'paid' as const,
    };
  } else if (idx === 1 || idx === 2) {
    return {
      ...item,
      status: 'overdue' as const,
      daysOverdue: 68,
    };
  }
  return item;
});

export const SEED_LOANS: Loan[] = [
  {
    id: 'LOG-2026-000001',
    loanNumber: 'LOG-2026-000001',
    applicationId: 'APP-2026-000001',
    customerId: 'CUS-2026-000001',
    loanProductId: 'LP-001',
    collateralId: 'COL-2026-000145',
    branchId: 'BR-001',
    principal: 600000,
    interestRatePerMonth: 3.5,
    interestMethod: 'flat_rate',
    durationMonths: 12,
    repaymentFrequency: 'monthly',
    installmentAmount: log1Calc.installmentAmount,
    totalInterest: log1Calc.totalInterest,
    processingFee: log1Calc.processingFee,
    insuranceFee: log1Calc.insuranceFee,
    totalPayable: log1Calc.totalPayable,
    totalPaid: log1Calc.installmentAmount * 6 + log1Calc.totalFees,
    outstandingPrincipal: 300000,
    outstandingInterest: log1Calc.totalInterest / 2,
    outstandingFees: 0,
    outstandingPenalties: 0,
    totalOutstanding: 405000,
    disbursementDate: '2026-02-22',
    disbursementMethod: 'bank',
    disbursementReference: 'EFT-KCB-2026-0222',
    maturityDate: '2027-02-22',
    nextPaymentDate: '2026-09-22',
    status: 'active',
    daysInArrears: 0,
    loanOfficerId: 'USR-004',
    schedule: updatedSchedule1,
    createdAt: '2026-02-22',
  },
  {
    id: 'PROP-2026-000002',
    loanNumber: 'PROP-2026-000002',
    applicationId: 'APP-2026-000002',
    customerId: 'CUS-2026-000002',
    loanProductId: 'LP-002',
    collateralId: 'COL-2026-000146',
    branchId: 'BR-001',
    principal: 5000000,
    interestRatePerMonth: 2.2,
    interestMethod: 'reducing_balance',
    durationMonths: 24,
    repaymentFrequency: 'monthly',
    installmentAmount: prop2Calc.installmentAmount,
    totalInterest: prop2Calc.totalInterest,
    processingFee: prop2Calc.processingFee,
    insuranceFee: prop2Calc.insuranceFee,
    totalPayable: prop2Calc.totalPayable,
    totalPaid: prop2Calc.installmentAmount * 5 + prop2Calc.totalFees,
    outstandingPrincipal: 4120000,
    outstandingInterest: 890000,
    outstandingFees: 0,
    outstandingPenalties: 0,
    totalOutstanding: 5010000,
    disbursementDate: '2026-03-08',
    disbursementMethod: 'bank',
    disbursementReference: 'RTGS-EQB-2026-0308',
    maturityDate: '2028-03-08',
    nextPaymentDate: '2026-09-08',
    status: 'active',
    daysInArrears: 0,
    loanOfficerId: 'USR-004',
    schedule: updatedSchedule2,
    createdAt: '2026-03-08',
  },
  {
    id: 'LOG-2026-000003',
    loanNumber: 'LOG-2026-000003',
    applicationId: 'APP-2026-000004',
    customerId: 'CUS-2026-000003',
    loanProductId: 'LP-001',
    collateralId: 'COL-2026-000147',
    branchId: 'BR-004',
    principal: 1000000,
    interestRatePerMonth: 3.5,
    interestMethod: 'flat_rate',
    durationMonths: 12,
    repaymentFrequency: 'monthly',
    installmentAmount: overdueLoanCalc.installmentAmount,
    totalInterest: overdueLoanCalc.totalInterest,
    processingFee: overdueLoanCalc.processingFee,
    insuranceFee: overdueLoanCalc.insuranceFee,
    totalPayable: overdueLoanCalc.totalPayable,
    totalPaid: overdueLoanCalc.installmentAmount + overdueLoanCalc.totalFees,
    outstandingPrincipal: 916667,
    outstandingInterest: 385000,
    outstandingFees: 0,
    outstandingPenalties: 42000,
    totalOutstanding: 1343667,
    disbursementDate: '2026-02-14',
    disbursementMethod: 'mobile_money',
    disbursementReference: 'MPESA-QGH882109',
    maturityDate: '2027-02-14',
    nextPaymentDate: '2026-07-14',
    status: 'in_recovery',
    daysInArrears: 68,
    loanOfficerId: 'USR-004',
    schedule: updatedOverdueSchedule,
    createdAt: '2026-02-14',
  },
];

export const SEED_REPAYMENTS: Repayment[] = [
  {
    id: 'REC-2026-000001',
    receiptNumber: 'REC-2026-000001',
    loanId: 'LOG-2026-000001',
    customerId: 'CUS-2026-000001',
    branchId: 'BR-001',
    amount: 71000,
    paymentDate: '2026-08-22',
    paymentMethod: 'mobile_money',
    transactionReference: 'QGJ98234KL',
    principalAllocation: 50000,
    interestAllocation: 21000,
    feesAllocation: 0,
    penaltyAllocation: 0,
    receivedById: 'USR-007',
    receivedByName: 'Faith Chebet (Cashier)',
    notes: 'M-Pesa payment received for Installment #6.',
    status: 'posted',
    createdAt: '2026-08-22 14:10',
  },
  {
    id: 'REC-2026-000002',
    receiptNumber: 'REC-2026-000002',
    loanId: 'PROP-2026-000002',
    customerId: 'CUS-2026-000002',
    branchId: 'BR-001',
    amount: 271500,
    paymentDate: '2026-08-08',
    paymentMethod: 'bank_transfer',
    transactionReference: 'EFT-STANBIC-88319',
    principalAllocation: 178000,
    interestAllocation: 93500,
    feesAllocation: 0,
    penaltyAllocation: 0,
    receivedById: 'USR-007',
    receivedByName: 'Faith Chebet (Cashier)',
    notes: 'Stanbic Bank Standing Order processed.',
    status: 'posted',
    createdAt: '2026-08-08 11:30',
  },
  {
    id: 'REC-2026-000003',
    receiptNumber: 'REC-2026-000003',
    loanId: 'LOG-2026-000001',
    customerId: 'CUS-2026-000001',
    branchId: 'BR-001',
    amount: 71000,
    paymentDate: '2026-07-22',
    paymentMethod: 'mobile_money',
    transactionReference: 'QFA719289M',
    principalAllocation: 50000,
    interestAllocation: 21000,
    feesAllocation: 0,
    penaltyAllocation: 0,
    receivedById: 'USR-007',
    receivedByName: 'Faith Chebet (Cashier)',
    notes: 'M-Pesa payment received for Installment #5.',
    status: 'posted',
    createdAt: '2026-07-22 10:45',
  },
];

export const SEED_RECOVERY_CASES: RecoveryCase[] = [
  {
    id: 'RC-2026-000001',
    loanId: 'LOG-2026-000003',
    customerId: 'CUS-2026-000003',
    collateralId: 'COL-2026-000147',
    branchId: 'BR-004',
    daysOverdue: 68,
    overdueAmount: 284000,
    totalOutstanding: 1343667,
    status: 'collateral_recovery',
    recoveryOfficerId: 'USR-008',
    lastFollowUpDate: '2026-09-11',
    nextActionDate: '2026-09-18',
    actions: [
      {
        id: 'ACT-01',
        actionType: 'call',
        description: 'First reminder phone call to borrower',
        outcome: 'Borrower promised to pay by end of week but failed.',
        officerName: 'Michael Wafula',
        timestamp: '2026-07-25 10:15',
      },
      {
        id: 'ACT-02',
        actionType: 'demand_letter',
        description: 'Formal 14-Day Demand Notice dispatched via registered post and email',
        outcome: 'Demand notice delivered. No response from borrower.',
        officerName: 'Michael Wafula',
        timestamp: '2026-08-10 14:00',
      },
      {
        id: 'ACT-03',
        actionType: 'repossess_notice',
        description: 'Repossession warrant issued to licensed court bailiff',
        outcome: 'Vehicle KBZ 445T impounded and secured in Nakuru yard.',
        officerName: 'Michael Wafula',
        timestamp: '2026-09-02 16:30',
      },
    ],
    createdAt: '2026-07-20',
  },
];

export const SEED_CASH_ACCOUNTS: CashAccount[] = [
  {
    id: 'ACC-001',
    accountName: 'KCB Main Operating Account',
    accountType: 'bank',
    accountNumber: '1182940291',
    bankName: 'KCB Bank Kenya',
    branchId: 'BR-001',
    balance: 18450000,
    status: 'active',
  },
  {
    id: 'ACC-002',
    accountName: 'M-Pesa Collections Paybill (552200)',
    accountType: 'mobile_money_paybill',
    accountNumber: '552200',
    branchId: 'BR-001',
    balance: 3820400,
    status: 'active',
  },
  {
    id: 'ACC-003',
    accountName: 'Stanbic Disbursements Account',
    accountType: 'bank',
    accountNumber: '01002938491',
    bankName: 'Stanbic Bank Kenya',
    branchId: 'BR-001',
    balance: 24600000,
    status: 'active',
  },
  {
    id: 'ACC-004',
    accountName: 'Head Office Petty Cash Vault',
    accountType: 'cash_in_hand',
    accountNumber: 'CASH-VAULT-01',
    branchId: 'BR-001',
    balance: 450000,
    status: 'active',
  },
];

export const SEED_SETTINGS: SystemSettings = {
  platformName: 'DAVETECH',
  platformTitle: 'ERP',
  platformSubtitle: 'Property, Asset & Secured Lending',
  platformInitials: 'D',
  logoUrl: '',
  logoType: 'monogram',
  companyName: 'Davetech Solutions Limited',
  brandTagline: 'Technology • Innovation • Efficiency',
  companyAddress: 'Davetech Towers, 6th Floor, Upper Hill Road, Nairobi, Kenya',
  companyPhone: '+254 700 000 111 / +254 722 000 222',
  companyEmail: 'info@davetech.co.ke',
  companyWebsite: 'https://davetech.co.ke',
  kraPin: 'P051928472L',
  registrationNumber: 'CPR/2021/88492',
  currencyCode: 'KES',
  currencySymbol: 'KSh',
  financialYearStart: 'January 1',
  financialYearEnd: 'December 31',
  defaultLtvPct: 70,
  defaultGracePeriodDays: 5,
  defaultPenaltyRateMonthly: 5.0,
  paymentAllocationOrder: ['penalties', 'fees', 'interest', 'principal'],
  approvalLimits: {
    branchManager: 1000000,
    seniorOfficer: 5000000,
    seniorManagement: 50000000,
  },
  smsAlertsEnabled: true,
  emailAlertsEnabled: true,
  requireCollateralVerificationBeforeApproval: true,
  sessionTimeoutMinutes: 60,
  twoFactorAuthRequired: false,
  autoBackupEnabled: true,
  lastBackupDate: '2026-09-14 23:59',
};

export const SEED_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'LOG-001',
    userId: 'USR-007',
    userName: 'Faith Chebet',
    userRole: 'cashier',
    action: 'POST_REPAYMENT',
    module: 'repayments',
    recordId: 'REC-2026-000001',
    branchId: 'BR-001',
    details: 'Posted repayment of KES 71,000 for Loan LOG-2026-000001 (John Kamau Mwangi)',
    timestamp: '2026-08-22 14:10:22',
  },
  {
    id: 'LOG-002',
    userId: 'USR-003',
    userName: 'Kevin Kiprop',
    userRole: 'branch_manager',
    action: 'APPROVE_LOAN',
    module: 'approvals',
    recordId: 'APP-2026-000001',
    branchId: 'BR-001',
    details: 'Approved Logbook Loan application for KES 600,000 backed by Toyota Probox KCA 123A',
    timestamp: '2026-02-21 11:30:15',
  },
  {
    id: 'LOG-003',
    userId: 'USR-006',
    userName: 'Eng. Samuel Njoroge',
    userRole: 'valuation_officer',
    action: 'VERIFY_COLLATERAL',
    module: 'collateral',
    recordId: 'COL-2026-000145',
    branchId: 'BR-001',
    details: 'Completed physical and NTSA inspection for KCA 123A. FSV verified at KES 950,000.',
    timestamp: '2026-02-20 16:45:00',
  },
];

export const SEED_PROPERTIES: PropertyListing[] = [
  {
    id: 'PROP-001',
    title: 'Kitengela Prime 50x100 Plot with Ready Title',
    propertyType: 'land_plot',
    category: 'sale',
    location: 'Kitengela, Acacia Area',
    county: 'Kajiado',
    size: '50x100 ft (0.11 Acres)',
    price: 850000,
    titleDeedNumber: 'KJD/KTG/2024/89421',
    status: 'available',
    description: 'Prime fenced plot located 3.5km from Kitengela Namanga highway. Water and electricity on site. Ready freehold title deed for immediate transfer.',
    features: ['Fenced', 'Electricity on site', 'Water connected', 'Freehold Title', 'Near tarmac'],
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800',
    createdAt: '2026-01-10',
  },
  {
    id: 'PROP-002',
    title: 'Ruaka Luxury 2 Bedroom Apartment for Rent',
    propertyType: 'apartment',
    category: 'rent',
    location: 'Ruaka, Near Two Rivers Mall',
    county: 'Kiambu',
    size: '950 sq ft (2 Beds, 2 Baths)',
    price: 45000,
    deposit: 45000,
    status: 'occupied',
    description: 'Modern 2 bedroom master ensuite apartment with high-speed lifts, backup generator, ample parking, and 24/7 security near Two Rivers Mall.',
    features: ['Master Ensuite', 'Backup Generator', 'High-speed Lifts', 'Ample Parking', 'Borehole Water', '24/7 CCTV'],
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=800',
    tenantName: 'Grace Achieng',
    tenantPhone: '+254 722 334 556',
    leaseStart: '2025-06-01',
    leaseEnd: '2026-05-31',
    createdAt: '2025-05-15',
  },
  {
    id: 'PROP-003',
    title: 'Ngong Gated Community 3 Bedroom Bungalow',
    propertyType: 'house_rental',
    category: 'rent',
    location: 'Ngong, Vet',
    county: 'Kajiado',
    size: '1/8 Acre Plot (3 Bed House)',
    price: 65000,
    deposit: 65000,
    status: 'available',
    description: 'Spacious 3 bedroom standalone bungalow with a manicured lawn, perimeter wall, cabro paved parking, and stunning views of Ngong Hills.',
    features: ['Standalone Compound', 'Perimeter Wall', 'Cabro Parking', 'Master Ensuite', 'Garden'],
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800',
    createdAt: '2026-02-01',
  },
  {
    id: 'PROP-004',
    title: 'Juja Farm 1/8 Acre Residential Plots',
    propertyType: 'land_plot',
    category: 'sale',
    location: 'Juja Farm, Block 3',
    county: 'Kiambu',
    size: '50x100 ft',
    price: 380000,
    titleDeedNumber: 'KBU/JJF/2025/11024',
    status: 'available',
    description: 'Fast-developing residential area ideal for immediate settlement or speculation. Accessible via Thika Superhighway.',
    features: ['Beaconed', 'Graded Access Roads', 'Ready Title Deed', 'Primary School Nearby'],
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&q=80&w=800',
    createdAt: '2026-01-20',
  },
  {
    id: 'PROP-005',
    title: 'Kilimani Executive 3 Bedroom Furnished Apartment',
    propertyType: 'apartment',
    category: 'rent',
    location: 'Kilimani, Argwings Kodhek Rd',
    county: 'Nairobi',
    size: '1,400 sq ft',
    price: 120000,
    deposit: 120000,
    status: 'occupied',
    description: 'Fully furnished luxury apartment with swimming pool, gym, high-speed internet, and rooftop terrace.',
    features: ['Swimming Pool', 'Gym', 'Fully Furnished', 'Elevator', 'Intercom'],
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800',
    tenantName: 'David Mutua',
    tenantPhone: '+254 711 998 877',
    leaseStart: '2025-09-01',
    leaseEnd: '2026-08-31',
    createdAt: '2025-08-10',
  },
];

export const SEED_MAINTENANCE_REQUESTS: MaintenanceRequest[] = [
  {
    id: 'MAINT-001',
    propertyId: 'PROP-002',
    propertyTitle: 'Ruaka Luxury 2 Bedroom Apartment',
    tenantName: 'Grace Achieng',
    issue: 'Kitchen sink plumbing leak and slow drainage',
    priority: 'medium',
    status: 'resolved',
    cost: 2500,
    dateReported: '2026-03-01',
  },
  {
    id: 'MAINT-002',
    propertyId: 'PROP-005',
    propertyTitle: 'Kilimani Executive 3 Bedroom Furnished Apartment',
    tenantName: 'David Mutua',
    issue: 'Living room AC unit needs servicing',
    priority: 'low',
    status: 'pending',
    cost: 4500,
    dateReported: '2026-03-10',
  },
];

export const SEED_ITEM_AGREEMENTS: ItemLoanAgreement[] = [
  {
    id: 'AGR-ITEM-2026-000001',
    agreementNumber: 'DT/AGR/ITEM/2026/014',
    customerId: 'CUS-2026-000001',
    customerName: 'John Kamau Mwangi',
    customerPhone: '+254 721 001 122',
    customerIdNumber: '28475910',
    customerEmail: 'kamau.john@gmail.com',
    customerAddress: 'Ruaka Ridge Estate, House 42B, Kiambu',
    itemId: 'AST-2026-000007',
    itemType: 'tv',
    itemTitle: 'Sony Bravia 55" 4K UHD Smart Android TV',
    itemBrand: 'Sony',
    itemModel: 'Bravia KD-55X80K',
    itemSerialNumber: 'SN-SONY-55-98312A',
    itemCondition: 'Mint working condition (tested, zero screen defects)',
    itemMarketValue: 75000,
    itemForcedSaleValue: 52000,
    accessoriesIncluded: ['Smart Voice Remote', 'Power Cable', 'Original Table Stands', 'Swivel Wall Bracket'],
    custodyType: 'in_branch_vault',
    custodyLocation: 'Nairobi CBD Branch Vault Storage Rack B-02',
    principalAmount: 35000,
    durationMonths: 3,
    interestRateMonthly: 4.0,
    interestMethod: 'flat_rate',
    monthlyInstallment: 13067,
    totalInterest: 4200,
    totalPayable: 39200,
    processingFee: 1050,
    disbursedAmount: 33950,
    gracePeriodDays: 5,
    penaltyRateMonthly: 5.0,
    repaymentFrequency: 'monthly',
    status: 'signed',
    draftedBy: 'Kevin Kiprop (Branch Manager)',
    draftedAt: '2026-03-01 09:30',
    sentAt: '2026-03-01 10:15',
    sentVia: 'whatsapp',
    signedAt: '2026-03-01 11:20',
    signedByName: 'John Kamau Mwangi',
    clientSignatureData: 'ACCEPTED_DIGITALLY_JOHN_KAMAU_MWANGI_28475910',
    clientIpOrDevice: 'Mobile Safari / iOS 18.2 (197.232.88.14)',
    witnessName: 'Esther Njeri (Custody Officer)',
    lenderSignatoryName: 'Kevin Kiprop (Branch Manager)',
    notes: 'Client reviewed online and signed via client link. TV safely sealed in Branch Vault Locker B-02.',
    onlineShareableToken: 'item-agr-token-001-sony55',
  },
  {
    id: 'AGR-ITEM-2026-000002',
    agreementNumber: 'DT/AGR/ITEM/2026/015',
    customerId: 'CUS-2026-000003',
    customerName: 'Peter Mwangi Njoroge',
    customerPhone: '+254 733 445 566',
    customerIdNumber: '24118932',
    customerEmail: 'peter.njoroge@gmail.com',
    customerAddress: 'Section 58, Nakuru',
    itemId: 'AST-2026-000008',
    itemType: 'woofer',
    itemTitle: 'Tagwood 5.1ch High-Bass Multimedia Woofer System',
    itemBrand: 'Tagwood',
    itemModel: 'TAG-5100-PRO Bass',
    itemSerialNumber: 'SN-TGW-51-44910X',
    itemCondition: 'Good working condition, tested clear bass output on all channels',
    itemMarketValue: 28000,
    itemForcedSaleValue: 19500,
    accessoriesIncluded: ['5 Satellite Speakers', 'RCA to AUX Audio Cables', 'Remote Control', 'FM Antenna'],
    custodyType: 'in_branch_vault',
    custodyLocation: 'Nakuru Branch Electronics Safe Room Shelf #03',
    principalAmount: 12000,
    durationMonths: 2,
    interestRateMonthly: 4.5,
    interestMethod: 'flat_rate',
    monthlyInstallment: 6540,
    totalInterest: 1080,
    totalPayable: 13080,
    processingFee: 500,
    disbursedAmount: 11500,
    gracePeriodDays: 5,
    penaltyRateMonthly: 5.0,
    repaymentFrequency: 'monthly',
    status: 'sent_to_client',
    draftedBy: 'David Kimani (Credit Officer)',
    draftedAt: '2026-03-02 14:00',
    sentAt: '2026-03-02 14:30',
    sentVia: 'whatsapp',
    notes: 'Agreement link dispatched to Peter Mwangi via WhatsApp (+254 733 445 566). Awaiting client digital signature.',
    onlineShareableToken: 'item-agr-token-002-woofer',
  },
  {
    id: 'AGR-ITEM-2026-000003',
    agreementNumber: 'DT/AGR/ITEM/2026/016',
    customerId: 'CUS-2026-000002',
    customerName: 'Grace Wanjiku Kariuki',
    customerPhone: '+254 711 223 344',
    customerIdNumber: '31092841',
    customerEmail: 'grace.kariuki@apexventures.co.ke',
    customerAddress: 'Riverside Park Apartments, Block C, Nairobi',
    itemId: 'AST-2026-000009',
    itemType: 'chair',
    itemTitle: 'Executive 7-Seater Chesterfield Living Room Sofa Suite',
    itemBrand: 'Victoria Courts Custom',
    itemModel: 'Chesterfield Royal 7-Piece',
    itemSerialNumber: 'TAG-CHT-FURN-009',
    itemCondition: 'Mint condition, pristine velvet fabric with solid oak framing',
    itemMarketValue: 160000,
    itemForcedSaleValue: 110000,
    accessoriesIncluded: ['6 Accent Velvet Throw Cushions', 'Manufacturer Warranty Card'],
    custodyType: 'held_by_borrower_chattel',
    custodyLocation: 'Borrower Residence - Ruaka Ridge Estate House 42B',
    principalAmount: 60000,
    durationMonths: 6,
    interestRateMonthly: 3.5,
    interestMethod: 'flat_rate',
    monthlyInstallment: 12100,
    totalInterest: 12600,
    totalPayable: 72600,
    processingFee: 1800,
    disbursedAmount: 58200,
    gracePeriodDays: 7,
    penaltyRateMonthly: 4.0,
    repaymentFrequency: 'monthly',
    status: 'draft',
    draftedBy: 'Kevin Kiprop (Branch Manager)',
    draftedAt: '2026-03-05 16:45',
    notes: 'Pledged under Chattels Transfer Act Cap 28 with right of inspection and registered chattel tag DT-CHT-009. Ready to send to client.',
    onlineShareableToken: 'item-agr-token-003-furniture',
  },
];


